[package]
name = "carbot"
version = "0.1.0"
authors = ["buffet <niclas@countingsort.com>"]

[dependencies]
env_logger = "0.6.0"
kankyo = "0.2.0"
log = "0.4.0"
serenity = { version = "0.5.11", features = ["cache", "framework", "standard_framework"] }
